import Link from "next/link";
import { ArrowRight, CreditCard, Plus, RefreshCw } from "lucide-react";
import { EventStatus } from "@/generated/prisma/client";
import { Button } from "@/components/ui/button";
import { EmptyState } from "@/components/shared/empty-state";
import { StatCard } from "@/components/shared/stat-card";
import { PaymentStatusBadge } from "@/components/payments/payment-status-badge";
import { RecalculatePaymentsButton } from "@/components/payments/recalculate-payments-button";
import { formatMoney } from "@/lib/payments/format";
import {
  formatActivityCostType,
  formatAllocationMethod,
  formatCostScope,
} from "@/lib/payments/labels";
import { toAllocationPaymentStatus } from "@/lib/payments/status-labels";
import { summariseAllocations, getOrganiserPaymentsPageData } from "@/lib/payments";
import { SendPaymentReminderButton } from "@/components/emails/send-payment-reminder-button";
import { GuestOfHonourBadge } from "@/components/guests/guest-of-honour-badge";
import { getOrganiserEvent } from "@/lib/events";

function PaymentItemCard({
  eventId,
  item,
}: {
  eventId: string;
  item: Awaited<
    ReturnType<typeof getOrganiserPaymentsPageData>
  >["paymentItems"][number];
}) {
  const itemSummary = summariseAllocations(item.allocations);
  const paidCount = item.allocations.filter(
    (allocation) =>
      allocation.status === "PAID" ||
      allocation.amountPaidCents >= allocation.amountCents,
  ).length;

  return (
    <Link
      href={`/events/${eventId}/payments/${item.id}`}
      className="buxmate-card block p-6 transition-shadow hover:shadow-md"
    >
      <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
        <div>
          <div className="flex flex-wrap items-center gap-2">
            <h4 className="font-heading text-lg font-semibold">{item.title}</h4>
            {item.isAutoGenerated ? (
              <span className="rounded-full bg-muted px-2 py-0.5 text-xs text-muted-foreground">
                From activity
              </span>
            ) : null}
          </div>
          <p className="mt-1 text-sm text-muted-foreground">
            {formatCostScope(item.costScope)} ·{" "}
            {formatAllocationMethod(
              item.allocationMethod,
              item.excludeGuestOfHonour,
            )}
          </p>
          {item.activity ? (
            <p className="mt-1 text-sm text-muted-foreground">
              {item.activity.title}
              {item.activity.costType
                ? ` · ${formatActivityCostType(item.activity.costType)}`
                : null}
            </p>
          ) : null}
          <p className="mt-2 text-sm font-medium">
            {formatMoney(item.amountCents)} total · {item.allocations.length}{" "}
            guests · {paidCount} paid
          </p>
          <p className="mt-1 text-sm text-muted-foreground">
            {formatMoney(itemSummary.outstanding)} outstanding
          </p>
        </div>
        <ArrowRight className="size-4 shrink-0 text-primary" aria-hidden />
      </div>
    </Link>
  );
}

export default async function EventPaymentsPage({
  params,
}: {
  params: Promise<{ eventId: string }>;
}) {
  const { eventId } = await params;
  const [event, data] = await Promise.all([
    getOrganiserEvent(eventId),
    getOrganiserPaymentsPageData(eventId),
  ]);

  const canAdd = event.status !== EventStatus.ARCHIVED;
  const { activityCosts, sharedCosts, guestBalances, summary, needsReviewCount } =
    data;

  return (
    <main className="mx-auto max-w-6xl px-4 py-8 sm:px-6">
      <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
        <div>
          <p className="text-xs uppercase tracking-wider text-primary">
            {event.name}
          </p>
          <h2 className="mt-1 font-heading text-xl font-semibold">Payments</h2>
          <p className="mt-1 max-w-2xl text-sm text-muted-foreground">
            Automatically calculated from RSVPs and shared costs. Mark payments
            manually as guests pay the organiser.
          </p>
        </div>
        <div className="flex flex-wrap gap-2">
          {canAdd ? <RecalculatePaymentsButton eventId={eventId} /> : null}
          {summary.outstanding > 0 && canAdd ? (
            <SendPaymentReminderButton eventId={eventId} mode="bulk" />
          ) : null}
          {canAdd ? (
            <Button className="rounded-full normal-case tracking-normal" asChild>
              <Link href={`/events/${eventId}/payments/new`}>
                <Plus className="size-4" aria-hidden />
                Add shared cost
              </Link>
            </Button>
          ) : null}
        </div>
      </div>

      {needsReviewCount > 0 ? (
        <div className="mt-6 rounded-2xl border border-border/70 bg-brand-muted/40 p-4 text-sm text-muted-foreground">
          {needsReviewCount} allocation{needsReviewCount === 1 ? "" : "s"} may
          need a review after RSVP changes. Paid amounts are kept as-is.
        </div>
      ) : null}

      <section className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <StatCard
          label="Total cost"
          value={formatMoney(summary.totalCost)}
          hint="Activities + shared costs"
          icon={CreditCard}
        />
        <StatCard
          label="Allocated"
          value={formatMoney(summary.allocated)}
          hint="Split across guests"
          icon={CreditCard}
        />
        <StatCard
          label="Paid"
          value={formatMoney(summary.paid)}
          icon={CreditCard}
        />
        <StatCard
          label="Outstanding"
          value={formatMoney(summary.outstanding)}
          icon={CreditCard}
        />
      </section>

      <section className="mt-10">
        <h3 className="font-heading text-lg font-semibold">Activity costs</h3>
        <p className="mt-1 text-sm text-muted-foreground">
          Based on activity pricing and who is marked Going.
        </p>
        {activityCosts.length > 0 ? (
          <div className="mt-4 grid gap-4">
            {activityCosts.map((item) => (
              <PaymentItemCard key={item.id} eventId={eventId} item={item} />
            ))}
          </div>
        ) : (
          <EmptyState
            className="mt-4"
            icon={CreditCard}
            title="No activity costs yet"
            description="Add a cost to an activity and guests will be charged based on their RSVP."
            action={
              canAdd ? (
                <Button className="rounded-full normal-case tracking-normal" asChild>
                  <Link href={`/events/${eventId}/activities/new`}>
                    Add activity
                  </Link>
                </Button>
              ) : undefined
            }
          />
        )}
      </section>

      <section className="mt-10">
        <h3 className="font-heading text-lg font-semibold">Shared costs</h3>
        <p className="mt-1 text-sm text-muted-foreground">
          Event-wide expenses like group gifts, transport or supplies.
        </p>
        {sharedCosts.length > 0 ? (
          <div className="mt-4 grid gap-4">
            {sharedCosts.map((item) => (
              <PaymentItemCard key={item.id} eventId={eventId} item={item} />
            ))}
          </div>
        ) : (
          <EmptyState
            className="mt-4"
            icon={RefreshCw}
            title="No shared costs yet"
            description="Add a shared cost and split it across guests — optionally excluding the guest of honour."
            action={
              canAdd ? (
                <Button className="rounded-full normal-case tracking-normal" asChild>
                  <Link href={`/events/${eventId}/payments/new`}>
                    Add shared cost
                  </Link>
                </Button>
              ) : undefined
            }
          />
        )}
      </section>

      {guestBalances.length > 0 ? (
        <section className="mt-10">
          <h3 className="font-heading text-lg font-semibold">Guest balances</h3>
          <div className="mt-4 space-y-3">
            {guestBalances.map((guest) => (
              <div
                key={guest.guestId}
                className="buxmate-card flex flex-col gap-3 p-4 sm:flex-row sm:items-center sm:justify-between"
              >
                <div>
                  <p className="flex flex-wrap items-center gap-2 font-medium">
                    {guest.name}
                    {guest.isGuestOfHonour ? <GuestOfHonourBadge /> : null}
                  </p>
                  <p className="mt-1 text-sm text-muted-foreground">
                    Owed {formatMoney(guest.owed)} · Paid {formatMoney(guest.paid)}{" "}
                    · Outstanding {formatMoney(guest.outstanding)}
                  </p>
                </div>
                <div className="flex flex-wrap items-center gap-2">
                  <PaymentStatusBadge
                    status={toAllocationPaymentStatus(
                      guest.paymentStatus as "PENDING" | "PARTIAL" | "PAID",
                    )}
                  />
                  {canAdd && guest.outstanding > 0 ? (
                    <SendPaymentReminderButton
                      eventId={eventId}
                      mode="guest"
                      guestId={guest.guestId}
                      guestName={guest.name}
                      outstandingCents={guest.outstanding}
                    />
                  ) : null}
                </div>
              </div>
            ))}
          </div>
        </section>
      ) : null}
    </main>
  );
}
