import { notFound } from "next/navigation";
import {
  ActivityStatus,
  GuestStatus,
  PaymentCostScope,
  PaymentItemStatus,
  PaymentStatus,
} from "@/generated/prisma/client";
import { deriveAllocationStatus } from "@/lib/payments/format";
import { countAllocationsNeedingReview } from "@/lib/payments/recalculate-event-payments";
import { prisma } from "@/lib/prisma";
import { getOrganiserEvent } from "@/lib/events";

export const paymentItemSelect = {
  id: true,
  eventId: true,
  activityId: true,
  title: true,
  description: true,
  amountCents: true,
  costScope: true,
  allocationMethod: true,
  excludeGuestOfHonour: true,
  isAutoGenerated: true,
  status: true,
  createdAt: true,
  updatedAt: true,
  activity: {
    select: {
      id: true,
      title: true,
      costType: true,
      costCents: true,
    },
  },
  allocations: {
    select: {
      id: true,
      guestId: true,
      amountCents: true,
      amountPaidCents: true,
      status: true,
      paidAt: true,
      isManualOverride: true,
      overrideReason: true,
      needsReview: true,
      guest: {
        select: {
          id: true,
          name: true,
          status: true,
          isGuestOfHonour: true,
        },
      },
    },
  },
} as const;

export function summariseAllocations(
  allocations: {
    amountCents: number;
    amountPaidCents: number;
    status: PaymentStatus;
  }[],
) {
  let allocated = 0;
  let paid = 0;

  for (const allocation of allocations) {
    allocated += allocation.amountCents;
    paid += allocation.amountPaidCents;
  }

  return {
    allocated,
    paid,
    outstanding: Math.max(0, allocated - paid),
  };
}

export async function getOrganiserPaymentsPageData(eventId: string) {
  await getOrganiserEvent(eventId);

  const [paymentItems, guests, needsReviewCount] = await Promise.all([
    prisma.paymentItem.findMany({
      where: { eventId, status: PaymentItemStatus.ACTIVE },
      orderBy: [{ isAutoGenerated: "desc" }, { createdAt: "desc" }],
      select: paymentItemSelect,
    }),
    prisma.eventGuest.findMany({
      where: { eventId, status: { not: GuestStatus.ARCHIVED } },
      orderBy: { name: "asc" },
      select: {
        id: true,
        name: true,
        status: true,
        isGuestOfHonour: true,
        paymentAllocations: {
          where: {
            paymentItem: { eventId, status: PaymentItemStatus.ACTIVE },
          },
          select: {
            amountCents: true,
            amountPaidCents: true,
            status: true,
          },
        },
      },
    }),
    countAllocationsNeedingReview(eventId),
  ]);

  const activityCosts = paymentItems.filter(
    (item) =>
      item.costScope === PaymentCostScope.ACTIVITY || item.isAutoGenerated,
  );
  const sharedCosts = paymentItems.filter(
    (item) =>
      item.costScope === PaymentCostScope.EVENT_WIDE && !item.isAutoGenerated,
  );

  const eventTotals = paymentItems.reduce(
    (acc, item) => {
      acc.totalCost += item.amountCents;
      const itemSummary = summariseAllocations(item.allocations);
      acc.allocated += itemSummary.allocated;
      acc.paid += itemSummary.paid;
      return acc;
    },
    { totalCost: 0, allocated: 0, paid: 0 },
  );

  const guestBalances = guests.map((guest) => {
    const summary = summariseAllocations(guest.paymentAllocations);
    const status = deriveAllocationStatus(summary.allocated, summary.paid);
    return {
      guestId: guest.id,
      name: guest.name,
      guestStatus: guest.status,
      isGuestOfHonour: guest.isGuestOfHonour,
      owed: summary.allocated,
      paid: summary.paid,
      outstanding: summary.outstanding,
      paymentStatus: status,
    };
  });

  return {
    paymentItems,
    activityCosts,
    sharedCosts,
    guestBalances,
    needsReviewCount,
    summary: {
      totalCost: eventTotals.totalCost,
      allocated: eventTotals.allocated,
      paid: eventTotals.paid,
      outstanding: Math.max(0, eventTotals.allocated - eventTotals.paid),
    },
  };
}

export async function getOrganiserPaymentItem(
  eventId: string,
  paymentItemId: string,
) {
  await getOrganiserEvent(eventId);

  const item = await prisma.paymentItem.findFirst({
    where: { id: paymentItemId, eventId },
    select: paymentItemSelect,
  });

  if (!item) {
    notFound();
  }

  return item;
}

export async function getEventPaymentSummary(eventId: string) {
  const data = await getOrganiserPaymentsPageData(eventId);
  return {
    ...data.summary,
    needsReviewCount: data.needsReviewCount,
  };
}

export async function getGuestPaymentData(
  eventId: string,
  guestId: string,
) {
  const allocations = await prisma.paymentAllocation.findMany({
    where: {
      guestId,
      paymentItem: {
        eventId,
        status: PaymentItemStatus.ACTIVE,
      },
    },
    orderBy: { paymentItem: { createdAt: "desc" } },
    select: {
      id: true,
      amountCents: true,
      amountPaidCents: true,
      status: true,
      paidAt: true,
      paymentItem: {
        select: {
          id: true,
          title: true,
          description: true,
          costScope: true,
          isAutoGenerated: true,
          activity: { select: { title: true } },
        },
      },
    },
  });

  const activityAllocations = allocations.filter(
    (allocation) =>
      allocation.paymentItem.costScope === PaymentCostScope.ACTIVITY ||
      allocation.paymentItem.isAutoGenerated,
  );
  const sharedAllocations = allocations.filter(
    (allocation) =>
      allocation.paymentItem.costScope === PaymentCostScope.EVENT_WIDE &&
      !allocation.paymentItem.isAutoGenerated,
  );

  const summary = summariseAllocations(allocations);

  const event = await prisma.event.findUnique({
    where: { id: eventId },
    select: { paymentInstructions: true },
  });

  return {
    allocations,
    activityAllocations,
    sharedAllocations,
    summary,
    paymentInstructions: event?.paymentInstructions ?? null,
  };
}

export async function getActiveActivitiesForPaymentForm(eventId: string) {
  return prisma.activity.findMany({
    where: { eventId, status: ActivityStatus.ACTIVE },
    orderBy: { startsAt: "asc" },
    select: { id: true, title: true, startsAt: true },
  });
}
