"use server";

import { revalidatePath } from "next/cache";
import { notFound } from "next/navigation";
import {
  EventStatus,
  PaymentAllocationMethod,
  PaymentCostScope,
  PaymentItemStatus,
  PaymentStatus,
} from "@/generated/prisma/client";
import { auditLog } from "@/lib/audit";
import { assertEventOwned } from "@/lib/activities";
import { dollarsToCents } from "@/lib/payments/format";
import { previewPaymentItemAllocations } from "@/lib/payments/preview";
import { recalculateEventPayments, recalculatePaymentItem } from "@/lib/payments/recalculate-event-payments";
import { resolveEligibleGuestIds } from "@/lib/payments/allocation-engine";
import { prisma } from "@/lib/prisma";
import { requireVerifiedOrganiser } from "@/lib/session";
import {
  createPaymentItemSchema,
  overrideAllocationSchema,
  paymentPreviewSchema,
  updatePaymentItemSchema,
  type CreatePaymentItemInput,
  type OverrideAllocationInput,
  type UpdatePaymentItemInput,
} from "@/lib/validations/payment";

type ActionResult =
  | { success: true; paymentItemId: string }
  | { success: false; error: string };

type SimpleResult =
  | { success: true }
  | { success: false; error: string };

async function getOwnedPaymentItemOrNotFound(
  eventId: string,
  paymentItemId: string,
  organiserId: string,
) {
  const item = await prisma.paymentItem.findFirst({
    where: {
      id: paymentItemId,
      eventId,
      event: { organiserId },
    },
    select: { id: true, status: true, isAutoGenerated: true },
  });

  if (!item) {
    notFound();
  }

  return item;
}

async function getOwnedAllocationOrNotFound(
  eventId: string,
  allocationId: string,
  organiserId: string,
) {
  const allocation = await prisma.paymentAllocation.findFirst({
    where: {
      id: allocationId,
      paymentItem: { eventId, event: { organiserId } },
    },
    select: {
      id: true,
      guestId: true,
      amountCents: true,
      amountPaidCents: true,
      paymentItemId: true,
    },
  });

  if (!allocation) {
    notFound();
  }

  return allocation;
}

function revalidatePaymentPaths(eventId: string, paymentItemId?: string) {
  revalidatePath(`/events/${eventId}`);
  revalidatePath(`/events/${eventId}/payments`);
  if (paymentItemId) {
    revalidatePath(`/events/${eventId}/payments/${paymentItemId}`);
    revalidatePath(`/events/${eventId}/payments/${paymentItemId}/edit`);
  }
}

async function revalidateGuestEventPaths(eventId: string) {
  const event = await prisma.event.findUnique({
    where: { id: eventId },
    select: { slug: true },
  });
  if (event?.slug) {
    revalidatePath(`/e/${event.slug}`);
  }
}

export async function previewPaymentItem(
  eventId: string,
  input: CreatePaymentItemInput,
) {
  const session = await requireVerifiedOrganiser();
  const parsed = paymentPreviewSchema.safeParse(input);

  if (!parsed.success) {
    return { success: false as const, error: "Please check the form and try again." };
  }

  await assertEventOwned(eventId, session.user.id);

  const preview = await previewPaymentItemAllocations(eventId, parsed.data);

  return { success: true as const, preview };
}

export async function createPaymentItem(
  eventId: string,
  input: CreatePaymentItemInput,
): Promise<ActionResult> {
  const session = await requireVerifiedOrganiser();
  const parsed = createPaymentItemSchema.safeParse(input);

  if (!parsed.success) {
    return { success: false, error: "Please check the form and try again." };
  }

  const event = await assertEventOwned(eventId, session.user.id);

  if (event.status === EventStatus.ARCHIVED) {
    return {
      success: false,
      error: "Cannot add payments to an archived event.",
    };
  }

  const data = parsed.data;
  const activityId = data.activityId || null;

  if (activityId) {
    const activity = await prisma.activity.findFirst({
      where: { id: activityId, eventId },
      select: { id: true },
    });
    if (!activity) {
      return { success: false, error: "Selected activity was not found." };
    }
  }

  const guestIds = await resolveEligibleGuestIds(
    eventId,
    data.allocationMethod as PaymentAllocationMethod,
    {
      activityId,
      excludeGuestOfHonour: data.excludeGuestOfHonour,
    },
  );

  if (guestIds.length === 0) {
    return {
      success: false,
      error:
        data.allocationMethod === "ACTIVITY_GOING_GUESTS"
          ? "No guests with a Going RSVP for this activity. Ask guests to RSVP first, or choose a different split."
          : "Add guests before creating a payment item.",
    };
  }

  const amountCents = dollarsToCents(data.amount);

  const paymentItem = await prisma.paymentItem.create({
    data: {
      eventId,
      activityId,
      title: data.title,
      description: data.description || null,
      amountCents,
      costScope: data.costScope as PaymentCostScope,
      allocationMethod: data.allocationMethod as PaymentAllocationMethod,
      excludeGuestOfHonour: data.excludeGuestOfHonour ?? false,
      isAutoGenerated: false,
      status: PaymentItemStatus.ACTIVE,
    },
    select: { id: true },
  });

  await recalculatePaymentItem(paymentItem.id);

  revalidatePaymentPaths(eventId, paymentItem.id);

  return { success: true, paymentItemId: paymentItem.id };
}

export async function updatePaymentItem(
  eventId: string,
  paymentItemId: string,
  input: UpdatePaymentItemInput,
): Promise<SimpleResult> {
  const session = await requireVerifiedOrganiser();
  const parsed = updatePaymentItemSchema.safeParse(input);

  if (!parsed.success) {
    return { success: false, error: "Please check the form and try again." };
  }

  await assertEventOwned(eventId, session.user.id);
  const owned = await getOwnedPaymentItemOrNotFound(
    eventId,
    paymentItemId,
    session.user.id,
  );

  if (owned.isAutoGenerated) {
    return {
      success: false,
      error: "Activity costs are managed from the activity. Edit the activity instead.",
    };
  }

  await prisma.paymentItem.update({
    where: { id: paymentItemId },
    data: {
      title: parsed.data.title,
      description: parsed.data.description || null,
    },
  });

  revalidatePaymentPaths(eventId, paymentItemId);

  return { success: true };
}

export async function overrideAllocation(
  eventId: string,
  allocationId: string,
  input: OverrideAllocationInput,
): Promise<SimpleResult> {
  const session = await requireVerifiedOrganiser();
  const parsed = overrideAllocationSchema.safeParse(input);

  if (!parsed.success) {
    return { success: false, error: "Please check the form and try again." };
  }

  await assertEventOwned(eventId, session.user.id);
  const allocation = await getOwnedAllocationOrNotFound(
    eventId,
    allocationId,
    session.user.id,
  );

  const amountCents = dollarsToCents(parsed.data.amountOwed);

  await prisma.paymentAllocation.update({
    where: { id: allocation.id },
    data: {
      amountCents,
      isManualOverride: true,
      overrideReason: parsed.data.overrideReason || null,
      needsReview: false,
      status:
        allocation.amountPaidCents >= amountCents
          ? PaymentStatus.PAID
          : allocation.amountPaidCents > 0
            ? PaymentStatus.PARTIAL
            : PaymentStatus.PENDING,
    },
  });

  revalidatePaymentPaths(eventId, allocation.paymentItemId);
  revalidateGuestEventPaths(eventId);

  auditLog("payment.allocation_overridden", {
    userId: session.user.id,
    eventId,
    allocationId,
    guestId: allocation.guestId,
  });

  return { success: true };
}

export async function clearAllocationOverride(
  eventId: string,
  allocationId: string,
): Promise<SimpleResult> {
  const session = await requireVerifiedOrganiser();
  await assertEventOwned(eventId, session.user.id);
  const allocation = await getOwnedAllocationOrNotFound(
    eventId,
    allocationId,
    session.user.id,
  );

  await prisma.paymentAllocation.update({
    where: { id: allocation.id },
    data: {
      isManualOverride: false,
      overrideReason: null,
    },
  });

  await recalculatePaymentItem(allocation.paymentItemId);

  revalidatePaymentPaths(eventId, allocation.paymentItemId);
  revalidateGuestEventPaths(eventId);

  return { success: true };
}

export async function recalculateEventPaymentAllocations(
  eventId: string,
): Promise<SimpleResult & { flagged?: number }> {
  const session = await requireVerifiedOrganiser();
  await assertEventOwned(eventId, session.user.id);

  const result = await recalculateEventPayments(eventId);

  revalidatePaymentPaths(eventId);
  revalidateGuestEventPaths(eventId);

  return { success: true, flagged: result.flagged };
}

export async function markAllocationPaid(
  eventId: string,
  allocationId: string,
): Promise<SimpleResult> {
  const session = await requireVerifiedOrganiser();
  await assertEventOwned(eventId, session.user.id);
  const allocation = await getOwnedAllocationOrNotFound(
    eventId,
    allocationId,
    session.user.id,
  );

  await prisma.paymentAllocation.update({
    where: { id: allocation.id },
    data: {
      amountPaidCents: allocation.amountCents,
      status: PaymentStatus.PAID,
      paidAt: new Date(),
      needsReview: false,
    },
  });

  revalidatePaymentPaths(eventId, allocation.paymentItemId);
  revalidateGuestEventPaths(eventId);

  auditLog("payment.marked_paid", {
    userId: session.user.id,
    eventId,
    allocationId,
    guestId: allocation.guestId,
  });

  return { success: true };
}

export async function markAllocationUnpaid(
  eventId: string,
  allocationId: string,
): Promise<SimpleResult> {
  const session = await requireVerifiedOrganiser();
  await assertEventOwned(eventId, session.user.id);
  const allocation = await getOwnedAllocationOrNotFound(
    eventId,
    allocationId,
    session.user.id,
  );

  await prisma.paymentAllocation.update({
    where: { id: allocation.id },
    data: {
      amountPaidCents: 0,
      status: PaymentStatus.PENDING,
      paidAt: null,
    },
  });

  revalidatePaymentPaths(eventId, allocation.paymentItemId);
  revalidateGuestEventPaths(eventId);

  return { success: true };
}
