import Link from "next/link";
import { Pencil } from "lucide-react";
import { PaymentStatus } from "@/generated/prisma/client";
import { Button } from "@/components/ui/button";
import { AllocationActions } from "@/components/payments/allocation-actions";
import { AllocationOverrideForm } from "@/components/payments/allocation-override-form";
import { ManualOverrideBadge } from "@/components/payments/manual-override-badge";
import { PaymentStatusBadge } from "@/components/payments/payment-status-badge";
import { GuestOfHonourBadge } from "@/components/guests/guest-of-honour-badge";
import { formatMoney } from "@/lib/payments/format";
import {
  formatActivityCostType,
  formatAllocationMethod,
  formatCostScope,
} from "@/lib/payments/labels";
import { toAllocationPaymentStatus } from "@/lib/payments/status-labels";
import { getOrganiserPaymentItem, summariseAllocations } from "@/lib/payments";
import { getOrganiserEvent } from "@/lib/events";

export default async function PaymentItemDetailPage({
  params,
}: {
  params: Promise<{ eventId: string; paymentItemId: string }>;
}) {
  const { eventId, paymentItemId } = await params;
  const [event, item] = await Promise.all([
    getOrganiserEvent(eventId),
    getOrganiserPaymentItem(eventId, paymentItemId),
  ]);

  const itemSummary = summariseAllocations(item.allocations);
  const canEdit = !item.isAutoGenerated && event.status !== "ARCHIVED";

  return (
    <main className="mx-auto max-w-6xl px-4 py-8 sm:px-6">
      <div className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
        <div>
          <Link
            href={`/events/${eventId}/payments`}
            className="text-sm text-muted-foreground hover:text-foreground"
          >
            ← Payments
          </Link>
          <p className="mt-2 text-xs uppercase tracking-wider text-primary">
            {event.name}
          </p>
          <h1 className="mt-1 font-heading text-2xl font-semibold sm:text-3xl">
            {item.title}
          </h1>
          <p className="mt-1 text-sm text-muted-foreground">
            {formatCostScope(item.costScope)} ·{" "}
            {formatAllocationMethod(
              item.allocationMethod,
              item.excludeGuestOfHonour,
            )}
          </p>
          {item.activity ? (
            <p className="mt-1 text-sm text-muted-foreground">
              {item.activity.title}
              {item.activity.costType
                ? ` · ${formatActivityCostType(item.activity.costType)}`
                : null}
            </p>
          ) : null}
          {item.isAutoGenerated ? (
            <p className="mt-2 text-sm text-muted-foreground">
              Automatically calculated from activity cost and RSVPs. Edit the
              activity to change pricing.
            </p>
          ) : null}
        </div>
        {canEdit ? (
          <Button
            variant="outline"
            className="shrink-0 rounded-full normal-case tracking-normal"
            asChild
          >
            <Link href={`/events/${eventId}/payments/${paymentItemId}/edit`}>
              <Pencil className="size-4" aria-hidden />
              Edit
            </Link>
          </Button>
        ) : null}
      </div>

      <section className="buxmate-card p-6">
        <dl className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
          <div>
            <dt className="text-xs uppercase tracking-wider text-muted-foreground">
              Total
            </dt>
            <dd className="mt-1 font-medium">{formatMoney(item.amountCents)}</dd>
          </div>
          <div>
            <dt className="text-xs uppercase tracking-wider text-muted-foreground">
              Allocated
            </dt>
            <dd className="mt-1 font-medium">
              {formatMoney(itemSummary.allocated)}
            </dd>
          </div>
          <div>
            <dt className="text-xs uppercase tracking-wider text-muted-foreground">
              Paid
            </dt>
            <dd className="mt-1 font-medium">{formatMoney(itemSummary.paid)}</dd>
          </div>
          <div>
            <dt className="text-xs uppercase tracking-wider text-muted-foreground">
              Outstanding
            </dt>
            <dd className="mt-1 font-medium text-primary">
              {formatMoney(itemSummary.outstanding)}
            </dd>
          </div>
        </dl>
        {item.description ? (
          <p className="mt-4 text-sm text-muted-foreground">{item.description}</p>
        ) : null}
      </section>

      <section className="mt-8">
        <h2 className="font-heading text-lg font-semibold">Guest splits</h2>
        <div className="mt-4 space-y-3">
          {item.allocations.map((allocation) => {
            const isPaid =
              allocation.status === PaymentStatus.PAID ||
              allocation.amountPaidCents >= allocation.amountCents;
            const status = toAllocationPaymentStatus(allocation.status);

            return (
              <div key={allocation.id} className="buxmate-card p-4">
                <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
                  <div>
                    <p className="flex flex-wrap items-center gap-2 font-medium">
                      {allocation.guest.name}
                      {allocation.guest.isGuestOfHonour ? (
                        <GuestOfHonourBadge />
                      ) : null}
                      {allocation.isManualOverride ? (
                        <ManualOverrideBadge />
                      ) : null}
                      {allocation.needsReview ? (
                        <span className="rounded-full bg-amber-500/10 px-2 py-0.5 text-xs text-amber-700 dark:text-amber-300">
                          Needs review
                        </span>
                      ) : null}
                    </p>
                    <p className="mt-1 text-sm text-muted-foreground">
                      Owed {formatMoney(allocation.amountCents)} · Paid{" "}
                      {formatMoney(allocation.amountPaidCents)}
                    </p>
                    {allocation.overrideReason ? (
                      <p className="mt-1 text-sm text-muted-foreground">
                        {allocation.overrideReason}
                      </p>
                    ) : null}
                  </div>
                  <div className="flex flex-wrap items-center gap-2">
                    <PaymentStatusBadge status={status} />
                    {event.status !== "ARCHIVED" ? (
                      <AllocationActions
                        eventId={eventId}
                        allocationId={allocation.id}
                        isPaid={isPaid}
                      />
                    ) : null}
                  </div>
                </div>
                {event.status !== "ARCHIVED" ? (
                  <AllocationOverrideForm
                    eventId={eventId}
                    allocationId={allocation.id}
                    currentAmountCents={allocation.amountCents}
                    isManualOverride={allocation.isManualOverride}
                  />
                ) : null}
              </div>
            );
          })}
        </div>
      </section>
    </main>
  );
}
