import {
  ActivityCostType,
  ActivityStatus,
  PaymentAllocationMethod,
  PaymentCostScope,
  PaymentItemStatus,
} from "@/generated/prisma/client";
import { recalculatePaymentItem } from "@/lib/payments/recalculate-event-payments";
import { prisma } from "@/lib/prisma";

export async function syncActivityPaymentItem(activityId: string) {
  const activity = await prisma.activity.findUnique({
    where: { id: activityId },
    select: {
      id: true,
      eventId: true,
      title: true,
      costType: true,
      costCents: true,
      status: true,
    },
  });

  if (!activity) {
    return;
  }

  const existing = await prisma.paymentItem.findFirst({
    where: {
      eventId: activity.eventId,
      activityId: activity.id,
      isAutoGenerated: true,
    },
    select: { id: true },
  });

  const shouldArchive =
    activity.status === ActivityStatus.ARCHIVED ||
    activity.costType === ActivityCostType.FREE ||
    activity.costCents <= 0;

  if (shouldArchive) {
    if (existing) {
      await prisma.paymentItem.update({
        where: { id: existing.id },
        data: { status: PaymentItemStatus.ARCHIVED },
      });
      await recalculatePaymentItem(existing.id);
    }
    return;
  }

  const paymentData = {
    title: activity.title,
    description:
      "Automatically calculated from activity cost and guest RSVPs.",
    amountCents: activity.costCents,
    costScope: PaymentCostScope.ACTIVITY,
    allocationMethod: PaymentAllocationMethod.ACTIVITY_GOING_GUESTS,
    excludeGuestOfHonour: false,
    isAutoGenerated: true,
    status: PaymentItemStatus.ACTIVE,
  };

  let paymentItemId: string;

  if (existing) {
    await prisma.paymentItem.update({
      where: { id: existing.id },
      data: paymentData,
    });
    paymentItemId = existing.id;
  } else {
    const created = await prisma.paymentItem.create({
      data: {
        eventId: activity.eventId,
        activityId: activity.id,
        ...paymentData,
      },
      select: { id: true },
    });
    paymentItemId = created.id;
  }

  await recalculatePaymentItem(paymentItemId);
}
