import {
  ActivityCostType,
  ActivityStatus,
  GuestStatus,
  PaymentAllocationMethod,
  PaymentCostScope,
  RsvpStatus,
} from "@/generated/prisma/client";
import { splitAmountCents } from "@/lib/payments/format";
import { prisma } from "@/lib/prisma";

type ResolveOptions = {
  activityId?: string | null;
  excludeGuestOfHonour?: boolean;
  selectedGuestIds?: string[];
};

export async function resolveEligibleGuestIds(
  eventId: string,
  method: PaymentAllocationMethod,
  options: ResolveOptions = {},
): Promise<string[]> {
  const activeGuestFilter = {
    eventId,
    status: { not: GuestStatus.ARCHIVED },
  };

  let guestIds: string[] = [];

  switch (method) {
    case PaymentAllocationMethod.ACTIVITY_GOING_GUESTS: {
      if (!options.activityId) {
        return [];
      }

      const going = await prisma.activityRsvp.findMany({
        where: {
          activityId: options.activityId,
          status: RsvpStatus.GOING,
          guest: activeGuestFilter,
        },
        select: { guestId: true },
        orderBy: { guest: { name: "asc" } },
      });

      guestIds = going.map((row) => row.guestId);
      break;
    }
    case PaymentAllocationMethod.SELECTED_GUESTS: {
      if (!options.selectedGuestIds?.length) {
        return [];
      }

      const selected = await prisma.eventGuest.findMany({
        where: {
          id: { in: options.selectedGuestIds },
          ...activeGuestFilter,
        },
        select: { id: true },
        orderBy: { name: "asc" },
      });

      guestIds = selected.map((guest) => guest.id);
      break;
    }
    case PaymentAllocationMethod.ALL_ACTIVE_GUESTS_EXCLUDING_GUEST_OF_HONOUR: {
      const guests = await prisma.eventGuest.findMany({
        where: {
          ...activeGuestFilter,
          isGuestOfHonour: false,
        },
        select: { id: true },
        orderBy: { name: "asc" },
      });

      guestIds = guests.map((guest) => guest.id);
      break;
    }
    default: {
      const guests = await prisma.eventGuest.findMany({
        where: activeGuestFilter,
        select: { id: true },
        orderBy: { name: "asc" },
      });

      guestIds = guests.map((guest) => guest.id);
    }
  }

  if (
    options.excludeGuestOfHonour &&
    method !== PaymentAllocationMethod.ALL_ACTIVE_GUESTS_EXCLUDING_GUEST_OF_HONOUR
  ) {
    const honourGuests = await prisma.eventGuest.findMany({
      where: {
        id: { in: guestIds },
        isGuestOfHonour: true,
      },
      select: { id: true },
    });
    const honourSet = new Set(honourGuests.map((guest) => guest.id));
    guestIds = guestIds.filter((id) => !honourSet.has(id));
  }

  return guestIds;
}

type PaymentItemForCalculation = {
  amountCents: number;
  costScope: PaymentCostScope;
  isAutoGenerated: boolean;
  activity?: {
    costType: ActivityCostType;
    costCents: number;
    status: ActivityStatus;
  } | null;
};

export function calculateAllocationAmounts(
  paymentItem: PaymentItemForCalculation,
  guestIds: string[],
): Map<string, number> {
  const amounts = new Map<string, number>();

  if (guestIds.length === 0) {
    return amounts;
  }

  if (
    paymentItem.isAutoGenerated &&
    paymentItem.activity &&
    paymentItem.activity.status === ActivityStatus.ACTIVE
  ) {
    const { costType, costCents } = paymentItem.activity;

    if (costType === ActivityCostType.FIXED_PER_ATTENDING_GUEST) {
      for (const guestId of guestIds) {
        amounts.set(guestId, costCents);
      }
      return amounts;
    }

    if (costType === ActivityCostType.TOTAL_SPLIT_BY_ATTENDING_GUESTS) {
      const shares = splitAmountCents(costCents, guestIds.length);
      guestIds.forEach((guestId, index) => {
        amounts.set(guestId, shares[index] ?? 0);
      });
      return amounts;
    }

    return amounts;
  }

  const shares = splitAmountCents(paymentItem.amountCents, guestIds.length);
  guestIds.forEach((guestId, index) => {
    amounts.set(guestId, shares[index] ?? 0);
  });

  return amounts;
}

export function derivePaymentStatus(
  amountCents: number,
  amountPaidCents: number,
): "PENDING" | "PARTIAL" | "PAID" {
  if (amountPaidCents <= 0) {
    return "PENDING";
  }
  if (amountPaidCents >= amountCents) {
    return "PAID";
  }
  return "PARTIAL";
}
