import {
  PaymentAllocationMethod,
  PaymentCostScope,
} from "@/generated/prisma/client";
import {
  calculateAllocationAmounts,
  resolveEligibleGuestIds,
} from "@/lib/payments/allocation-engine";
import { prisma } from "@/lib/prisma";
import type { CreatePaymentItemInput } from "@/lib/validations/payment";
import { dollarsToCents } from "@/lib/payments/format";

export type PaymentAllocationPreviewRow = {
  guestId: string;
  guestName: string;
  isGuestOfHonour: boolean;
  amountCents: number;
};

export type PaymentAllocationPreview = {
  guests: PaymentAllocationPreviewRow[];
  totalAllocatedCents: number;
  amountPerGuestLabel: string;
};

export async function previewPaymentItemAllocations(
  eventId: string,
  input: CreatePaymentItemInput,
): Promise<PaymentAllocationPreview> {
  const activityId = input.activityId || null;
  const amountCents = dollarsToCents(input.amount);

  const guestIds = await resolveEligibleGuestIds(
    eventId,
    input.allocationMethod as PaymentAllocationMethod,
    {
      activityId,
      excludeGuestOfHonour: input.excludeGuestOfHonour,
    },
  );

  const guests = await prisma.eventGuest.findMany({
    where: { id: { in: guestIds } },
    select: { id: true, name: true, isGuestOfHonour: true },
    orderBy: { name: "asc" },
  });

  const amounts = calculateAllocationAmounts(
    {
      amountCents,
      costScope: input.costScope as PaymentCostScope,
      isAutoGenerated: false,
      activity: null,
    },
    guests.map((guest) => guest.id),
  );

  const rows: PaymentAllocationPreviewRow[] = guests.map((guest) => ({
    guestId: guest.id,
    guestName: guest.name,
    isGuestOfHonour: guest.isGuestOfHonour,
    amountCents: amounts.get(guest.id) ?? 0,
  }));

  const totalAllocatedCents = rows.reduce(
    (sum, row) => sum + row.amountCents,
    0,
  );

  const uniqueAmounts = [...new Set(rows.map((row) => row.amountCents))];
  const amountPerGuestLabel =
    uniqueAmounts.length === 1 && rows.length > 0
      ? "Equal split"
      : "Varies by guest";

  return {
    guests: rows,
    totalAllocatedCents,
    amountPerGuestLabel,
  };
}
